config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'new_user_registration' => 'devise/registrations#new_user_registration'

  resources :categories
  get 'categories/index'
  get 'categories/show'
  get 'categories/update'
  get 'categories/create'
  get 'categories/new'
  get 'categories/edit'
  get 'categories/destroy'
  

  get 'welcome/show/:id' => 'welcome#show', as: 'welcome_show'
  # resources :articles 



  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    include ImageUploader::Attachment.new(:image)
    
    validates :name, presence: {message: 'Ne doit pas etre vide'}   
    validates :content, presence:{message: 'Ne doit pas etre vide'} 
    validates :date, presence:{message: 'Ne doit pas etre vide'} 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  layout "blog/base"
  def index
    @title = "Page Articles"
    @categories = Category.all
    @user = current_user.Category.all
  end
  def show
    @category = Category.find(params[:id])
  end
  def update
      @title = "Page Modification"
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end  
  end
  def create
    @title = "Creation d'un article"
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "Article creer avec success"
      redirect_to categories_path(@category.id)
    else
        render 'new'
    end
     

  end
  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private 
  
  def category_params
    params.required(:category).permit(:name, :content, :date, :image)
  end

  private

  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
    layout "blog/base"
  def index
    @title = "Bienvenue dans mon blog"
    @categories = Category.all
  end

  def show
    @title = "Details d'un article"
    @category = Category.find(params[:id])
  end

  private 
  
  def category_params

    params.required(:category).permit(:name, :content)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<% @title = "Modifier un article" %>
<h1 class="text-center">Modifier votre article</h1>
<div class="container">
    <div class="row">
        <div class="col-lg-6 offset-3">
            <div class="card">
                <%  if @category.invalid?  %>
                    <div class="alert alert-danger">
                         <% @category.errors.full_messages.each do |message| %>
                            <%= message %>
                        <%end%>
                    </div>
                <%end%>
                <div class="card-body"> 
                    <%= form_for @category do |f| %>
                    <p>
                      <b><%= f.label :Titre_Article, class: 'form-label'  %></b>  
                        <%= f.text_field :name, class: 'form-control' %>
                    </p>
                     <p>
                      <b><%= f.label :Date_de_creation, class: 'form-label'  %>
                      </b>  
                        <%= f.date_field :date, class: 'form-control' %>
                    </p>
                     <p>
                      <b>
                        <%= f.label :Image, class: 'form-label'  %>
                      </b> 
                        <%= f.file_field :image, class: 'form-control' %>
                    </p>

                    <p>
                      <b><%= f.label :Description, class: 'form-label'  %> </b>
                        <%= f.text_area :content, class: 'form-control', placeholder: 'decrivez votre article' %>
                    </p>
                    

   
                    <p>
                        <button type="submit" class="btn btn-primary">Modifier</button>
                    </p>
                    <%end%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<div class="container">
<h1 class="text-center">Liste de mes articles</h1> <br>
        <a href="/" class="btn btn-link">Acceuil</a>
    <br>
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-striped table-hover table-responsive">
                <thead class="thead-dark">
                    <tr>
                    <th>Titre </th>
                    <th>Date</th>
                    <th>Contenu</th> 
                    <th>Image</th>
                    <th> Actions</th> 
                    </tr>
                    
                </thead>
                <tbody>
                    <% @categories.each do |category| %>
                    <tr>
                        <td><%= category.name%></td>
                        <td><%= category.content%></td>
                        <td><%= category.date%></td>
                        <td><%= image_tag category.image_url, height: 50%>  </td>
                        
                        <td> 
                        <a href="<%= edit_category_path(category.id) %>" class="btn btn-link">
                        Editer <i class="fa fa-home"></i>
                        </a>
                            <a href="<%= category_path(category.id) %>" class="btn btn-link"
                            data-confirm="Voulez-vous supprimer" data-method="delete">Supprimer</a>
                        </td>
                        
                        
                    </tr>

                    <%end%>
                </tbody>
            </table>
  
        </div>
    </div>
</div>

app/views/categories/new.html.erb
<% @title = "Creer un article" %>
<h1 class="text-center">Creer un nouveau article</h1>
<div class="container">
    <div class="row">
        <div class="col-lg-8 offset-2 jumbotron">
       <% if @category.errors.any? %>
            <div id="error_explanation">
                <div class="alert alert-danger">
                    Vous avez des erreurs dans le formulaire
                     <ul>
                        <% @category.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
           
            </div>
        <% end %>
               
            <div class="card">
                <div class="card-body"> 
                    <%= form_for @category do |f| %>
                    <p>
                      <b><%= f.label :Titre_Article, class: 'form-label'  %></b>  
                        <%= f.text_field :name, class: 'form-control' %>
                    </p>
                     <p>
                      <b><%= f.label :Date_de_creation, class: 'form-label'  %></b>  
                        <%= f.date_field :date, class: 'form-control' %>
                    </p>
                     <p>
                      <b><%= f.label :Image, class: 'form-label'  %></b>  
                        <%= f.hidden_field :image, value: @category.cached_image_data %>
                        <%= f.file_field :image, class: 'form-control' %>
                    </p>
                    <p>
                      <b><%= f.label :Description, class: 'form-label'  %> </b>
                        <%= f.text_area :content, class: 'form-control', placeholder: 'decrivez votre article' %>
                    </p>
                   
   
                    <p>
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    </p>
                    <%end%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "Authentifiez - vous"%> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="#">Authentification App</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav" style="margin-left: 800px">
              
              <%=  link_to "Inscription", new_user_registration_path, method: :get, class: 'nav-link active' %> 
              <%=  link_to "Connexion", new_user_session_path, method: :get, class: 'nav-link active' %> 
            </div>
          </div>
        </nav>
      <div class="container">
          <div class="row">
              <div class="col-lg-6 offset-2">
                    <p class="notice"><%= notice %></p>
                    <p class="alert"><%= alert %></p>
              </div>
          </div>
      </div>
    <%= yield %>

   
  </body>
</html>

app/views/layouts/blog/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="/">Mon blog  </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav" style="margin-left: 700px">
              
              <%= link_to "Creer un article",new_category_path, class: 'nav-link active' %>
              <%= link_to "Mes articles",categories_path, class: 'nav-link active' %>                
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%=  link_to "Déconnexion", destroy_user_session_path, method: :delete, class: 'nav-link active btn btn-danger' %>
            </div>
          </div>
        </nav>
      <div class="container">
          <div class="row">
              <div class="col-lg-6 offset-2">
                    <p class="notice"><%= notice %></p>
                    <p class="alert"><%= alert %></p>
                  <% if flash[:success]  %>
                    <div class="alert alert-success">
                      <%=  flash[:success] %>
                    </div> 
                  <% end %>
              </div>
          </div>
      </div>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-3 offset-8">
            <div class="card">
              <div class="card-header">
                  <h6>Infos de connexion</h6> 
                  <p><b>Email :  </b><%= current_user.email %>  <br>                  
                  </p>
              </div>
             
            </div>
        </div>
    </div> <br>
    <div class="row">
        <div class="col-lg-12 jumbotron">
            <h2 class="text-center">Retrouvevez les dernieres informations dans mon blog</h2> 
            <p>
            <b> What is Lorem Ipsum?</b> <br>    
                Lorem Ipsum is simply dummy text of the printing and 
                typesetting industry. Lorem Ipsum has been the industry's standard dummy 
                text ever since the 1500s, when an unknown printer took a galley of type and 
                scrambled it to make a type specimen book. It has survived not only five centuries,
                but also the leap into electronic typesetting, remaining essentially unchanged. 
                It was popularised in the 1960s with the release of Letraset sheets containing Lorem 
                Ipsum passages, and more recently with 
                desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>                    
        </div>
    </div>

     <div class="row mb-2">

  <%  @categories.each do |category| %>

    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0"><%= category.name%></h3>
          <div class="mb-1 text-muted"><%= category.date%></div>
          <p class="card-text mb-auto">
              <%= category.content %>
          </p>
          <p><a href="<%= welcome_show_url(category.id) %>" class="btn btn-link">Voir les details</a>    </p>
        </div>
        <div class="col-auto d-none d-lg-block">
             <%= image_tag category.image_url, width:"200",height:"250",preserveAspectRatio: "xMidYMid slice",
              focusable:"false",role:"img", aria_label: "Placeholder: Thumbnail" %>
             <rect width="100%" height="100%" fill="#55595c"/>
          
           
        </div>
      </div>
    </div>
  <%end%>



  </div>
</div>
</div>

app/views/welcome/show.html.erb
<% @title = "Details de l'article" %>
<div class="container">
    <div class="row">
        <div class="col-lg-3 offset-1">
            <%= image_tag @category.image_url, width:"200",height:"250",preserveAspectRatio: "xMidYMid slice",
              focusable:"false",role:"img", aria_label: "Placeholder: Thumbnail" %>     
        </div>
        <div class="col-lg-7">
           <h2><b><%= @category.name%></b></h2> 
            <p>
                <%= @category.content %>
            </p>

            <p>publié le : <%= @category.date%></p>

            <p> <a href="/" class="btn btn-link">Retour</a></p>
            
        </div>
    </div>
</div>
  